# Generated by Django 5.1.2 on 2024-10-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('youTubeLink', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
